In [247]:
#Data Input Pipeline
import numpy as np
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [248]:
x_test.shape

(10000, 28, 28)

In [285]:
#Data Made suitable for input
nClass = 10
nH = [256, 64]
nY = [10]
x_train_flat = x_train.reshape(x_train.shape[0],-1).T
x_test_flat = x_test.reshape(x_test.shape[0],-1).T
y_train_onehot = np.eye(nClass)[y_train].T
y_test_onehot = np.eye(nClass)[y_test].T
layers = nH + nY
limit = 0.0001
learning_rate = 0.01

In [268]:
y_train_onehot.shape

(10, 60000)

In [269]:
x_train_flat.shape
layers

[256, 64, 10]

In [270]:
#"#Define"
# Dataset must be of shape - [no of features, no of examples]
nY = nClass
nH = [50]     #neurons
nX = x_train_flat.shape[0]
m_train = x_train_flat.shape[1]

In [271]:
x_train_flat.shape

(784, 60000)

In [272]:
x_train_flat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [274]:
class deepfuzzy:
    W = []
    b = []
    parameters = dict()
    act = []
    def __init__(self, layers, test_data, train_data, y_train_onehot, y_test_onehot, no_of_examples, iterations):
        self.layers = layers
        self.test_data = test_data
        self.train_data = train_data[:][:no_of_examples]
        self.y_train_onehot = y_train_onehot
        self.y_test_onehot = y_test_onehot
        self.iter = iterations
        initialize(self, 'random')
    def train(self):
        for i in range(self.iter):
            forwardProp(self)
            compCost(self)
            backProp(self)
           # if(i%10 == 0):
            #    self.saveWeights()
    def saveWeights(self):
        np.save('W.npy',  self.parameters['W'])  
        np.save('b.npy', self.parameters['b'])
        my_dict_back = np.load('my_dict.npy')
        
    def loadWeights(self):
        self.W = np.load('W.npy')
        self.b = np.load('b.npy')
    
    def backProp(loss, opt):
        pass
        
        

In [275]:
def initialize(self, initializer = 'random'):
        #parameters = dict()
        W = []
        b = []
        np.random.seed(1)
        for i in range(len(self.layers)-1):
            W.append(np.random.randn(self.layers[i+1],self.layers[i])*0.01)
            b.append(np.random.randn(self.layers[i+1],1)*0.01)
        self.parameters['W'] = W
        self.parameters['b'] = b

In [276]:
def sigma(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0,x)

In [277]:
def forwardProp(self):
    self.act=[]
    self.act.append(self.train_data)
    for i in range(len(self.layers)-2):
        z = np.dot(self.parameters['W'][i], self.act[-1])
        self.act.append(sigma(z + self.parameters['b'][i]))  #sigmoid
    self.act.append(softmax(np.dot(self.parameters['W'][len(self.layers)-2], self.act[-1])))
    

In [278]:
def compCost(self):
    cost = -1.0/y_train_onehot.shape[1]*np.sum(np.dot(self.y_train_onehot,np.log(self.act[-1].T))+np.dot((1-self.y_train_onehot),np.log(1-self.act[-1]).T))
    print(cost)

In [280]:

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [281]:
def backProp(self):
    dAL = -np.divide(self.y_train_onehot, self.act[-1])+np.divide(1-self.y_train_onehot, 1-self.act[-1])
    
    dA_prev = dAL
    m = y_train_onehot.shape[1]
    for i in reversed(range(len(self.layers)-1)):
        dA = dA_prev 
        dZ = linear_activation_backward(dA,self.act[i+1],"sigmoid")
        dW = 1.0/m*np.dot(dZ, self.act[i].T)

        db = 1.0/m*np.sum(dZ,axis=1,keepdims=True)
        #print(db)
        dA_prev = np.dot(self.parameters['W'][i].T, dZ)
        self.parameters['W'][i] = self.parameters['W'][i] - learning_rate*dW
        self.parameters['b'][i] = self.parameters['b'][i] - learning_rate*db
        

In [282]:
def linear_activation_backward(dA,cache,activation):
    if(activation=="sigmoid"):
        act =  cache 
        return dA*act*(1-act)

In [283]:

test = deepfuzzy([784]+layers,x_test_flat, x_train_flat, y_train_onehot,y_test_onehot, 60000, 20)

In [ ]:
test.train()


32.515872123871176
32.51597104545968
32.51606948634523
32.516167416812756
32.51626480886748
32.51636163616691
32.51645787395513
32.51655349899947
32.516648489529345
32.51674282517728
32.51683648692194


In [176]:
test.act[-1]


array([[0.46169222, 0.4614836 , 0.46165243, ..., 0.46122511, 0.46149073,
        0.46119847],
       [0.46892141, 0.46921175, 0.46955194, ..., 0.46899174, 0.46976669,
        0.46869119],
       [0.47187014, 0.47184143, 0.47216815, ..., 0.47169907, 0.47212822,
        0.471608  ],
       ...,
       [0.46566315, 0.46578097, 0.46545652, ..., 0.46590741, 0.46531446,
        0.46543962],
       [0.47230168, 0.47283099, 0.47257155, ..., 0.47310496, 0.47289695,
        0.47267666],
       [0.48018227, 0.4802974 , 0.48071575, ..., 0.48039708, 0.48070743,
        0.48088176]])

In [153]:
test.y_train_onehot

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])