In [416]:
#Data Input Pipeline
import numpy as np
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [417]:
x_train.shape

(60000, 28, 28)

In [418]:
#Data Made suitable for input
nClass = 10
nH = [256, 64]
nY = [10]
x_train_flat = x_train.reshape(x_train.shape[0],-1).T
x_test_flat = x_test.reshape(x_test.shape[0],-1).T
y_train_onehot = np.eye(nClass)[y_train].T
y_test_onehot = np.eye(nClass)[y_test].T
layers = nH + nY
limit = 0.0001
learning_rate = 0.1

In [419]:
y_train_onehot.shape

(10, 60000)

In [420]:
x_train_flat.shape


(784, 60000)

In [421]:
#"#Define"
# Dataset must be of shape - [no of features, no of examples]
nY = nClass
nH = [50]     #neurons
nX = x_train_flat.shape[0]
m_train = x_train_flat.shape[1]

In [422]:
x_train_flat.shape

(784, 60000)

In [423]:
x_train_flat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [464]:
class deepfuzzy:
    W = []
    b = []
    parameters = dict()
    act = []
    def __init__(self, layers, test_data, train_data, y_train_onehot, y_test_onehot, no_of_examples, iterations):
        self.layers = layers
        self.test_data = test_data
        self.train_data = train_data[:, :no_of_examples]
        #print(self.train_data.shape)
        print("train_data",self.train_data)
        self.y_train_onehot = y_train_onehot[:][ :no_of_examples]
        self.y_test_onehot = y_test_onehot
        print("train_onehot",self.y_train_onehot)
        self.iter = iterations
        initialize(self, 'random')
    def train(self):
        for i in range(self.iter):
            forwardProp(self)
            compCost(self)
            #print(self.act[-1])
            #print(self.y_train_onehot)
            backProp(self)
           # if(i%10 == 0):
            #    self.saveWeights()
    def saveWeights(self):
        np.save('W.npy',  self.parameters['W'])  
        np.save('b.npy', self.parameters['b'])
        my_dict_back = np.load('my_dict.npy')
        
    def loadWeights(self):
        self.W = np.load('W.npy')
        self.b = np.load('b.npy')
    
    def backProp(loss, opt):
        pass
        
        

In [483]:
def initialize(self, initializer = 'random'):
        #parameters = dict()
        W = []
        b = []
        #np.random.seed(1)
        for i in range(len(self.layers)-1):
            W.append(np.random.rand(self.layers[i+1],self.layers[i])*1)
            b.append(np.random.rand(self.layers[i+1],1)*1)
        self.parameters['W'] = W
        self.parameters['b'] = b
        print("w", W)
        print("b", b)

In [484]:
def sigma(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0,x)

In [485]:
def forwardProp(self):
    self.act=[]
    self.act.append(self.train_data)
    for i in range(len(self.layers)-1):
        z = np.dot(self.parameters['W'][i], self.act[-1])
        self.act.append(sigma(z + self.parameters['b'][i]))  #sigmoid
    #self.act.append(softmax(np.dot(self.parameters['W'][len(self.layers)-2], self.act[-1])))
    #print("self.act", self.act)

In [486]:
def compCost(self):
    #print("y-train-oneshots_shape ", self.y_train_onehot.shape, self.act[-1].T)
    #print((1-self.y_train_onehot),np.log(1-self.act[-1]).T)
    cost = -1.0/y_train_onehot.shape[1]*np.sum(np.dot(self.y_train_onehot,np.log(self.act[-1].T))+np.dot((1-self.y_train_onehot),np.log(1-self.act[-1]).T))
    print(cost)
    print("self.act", self.act)
    #print(self.parameters['W'])
    #print(self.parameters['b'])

In [487]:

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [492]:
def backProp(self):
    dAL = -np.divide(self.y_train_onehot, self.act[-1])+np.divide(1-self.y_train_onehot, 1-self.act[-1])
    
    dA_prev = dAL
    m = self.y_train_onehot.shape[1]
    for i in reversed(range(len(self.layers)-1)):
        dA = dA_prev 
        dZ = linear_activation_backward(dA,self.act[i+1],"sigmoid")
        print("dZ",dZ)
        dW = 1.0/m*np.dot(dZ, self.act[i].T)
        print("dW",dW)
        db = 1.0/m*np.sum(dZ,axis=1)
        print("db",db)
        print("m",m)
        dA_prev = np.dot(self.parameters['W'][i].T, dZ)
        self.parameters['W'][i] = self.parameters['W'][i] - learning_rate*dW
        self.parameters['b'][i] = self.parameters['b'][i] - learning_rate*db
        

In [493]:
def linear_activation_backward(dA,cache,activation):
    if(activation=="sigmoid"):
        act =  cache 
        print("dA",dA)
        print("cache", cache)
        #return dA*act*(1-act)
        return np.multiply(np.multiply(dA, act), 1-act)

In [494]:

with open('and_y.txt') as file:
    array2d = [[float(digit) for digit in line.split()] for line in file]

test = deepfuzzy([2, 2, 1],x_test_flat, np.loadtxt('and.txt').T, np.matrix(array2d).T,y_test_onehot, 4, 1000)

train_data [[0. 0. 1. 1.]
 [0. 1. 0. 1.]]
train_onehot [[0. 0. 0. 1.]]
w [array([[0.16705373, 0.90883154],
       [0.70189819, 0.10950776]]), array([[0.6476292 , 0.32909777]])]
b [array([[0.09203357],
       [0.91368188]]), array([[0.45840924]])]


In [500]:
test.train()

7.093018280114512e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00569794, 0.17192468, 0.17455335, 0.88454515],
        [0.95353617, 0.68263904, 0.68820581, 0.18788191]]), matrix([[6.94142553e-04, 1.05317553e-02, 1.04745592e-02, 9.79467408e-01]])]
dA [[ 1.00069462  1.01064385  1.01058544 -1.02096302]]
cache [[6.94142553e-04 1.05317553e-02 1.04745592e-02 9.79467408e-01]]
dZ [[ 0.00069414  0.01053176  0.01047456 -0.02053259]]
dW [[-0.00362975  0.00280056]]
db [[0.00029197]]
m 4
dA [[ 0.0058089   0.08813456  0.08765592 -0.17182615]
 [-0.00342925 -0.0520297  -0.05174714  0.10143652]]
cache [[0.00569794 0.17192468 0.17455335 0.88454515]
 [0.95353617 0.68263904 0.68820581 0.18788191]]
dZ [[ 3.29102031e-05  1.25474163e-02  1.26298570e-02 -1.75477502e-02]
 [-1.51932756e-04 -1.12718692e-02 -1.11038266e-02  1.54774171e-02]]
dW [[-0.00122947 -0.00125008]
 [ 0.0010934   0.00105139]]
db [[ 0.00191561]
 [-0.00176255]]
m 4
7.09080160797936e-07
self.act [array([[0., 0., 1

dW [[-0.00121114 -0.00123145]
 [ 0.00107881  0.00103762]]
db [[ 0.00188669]
 [-0.00173823]]
m 4
6.983725214882321e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00564434, 0.17145513, 0.17406341, 0.88483074],
        [0.95392238, 0.68340315, 0.68891805, 0.18759201]]), matrix([[6.82468701e-04, 1.03707438e-02, 1.03149847e-02, 9.79781000e-01]])]
dA [[ 1.00068293  1.01047942  1.01042249 -1.02063624]]
cache [[6.82468701e-04 1.03707438e-02 1.03149847e-02 9.79781000e-01]]
dZ [[ 0.00068247  0.01037074  0.01031498 -0.020219  ]]
dW [[-0.00357824  0.00276292]]
db [[0.0002873]]
m 4
dA [[ 0.00572351  0.08697404  0.08650642 -0.16956626]
 [-0.00338107 -0.05137852 -0.05110228  0.10016854]]
cache [[0.00564434 0.17145513 0.17406341 0.88483074]
 [0.95392238 0.68340315 0.68891805 0.18759201]]
dZ [[ 3.21231095e-05  1.23553818e-02  1.24366251e-02 -1.72797002e-02]
 [-1.48613244e-04 -1.11164251e-02 -1.09517278e-02  1.52658111e-02]]
dW [[-0.00121077 -0.00123108]
 [ 0.00107852  0.00

 [-0.00333421 -0.05074314 -0.05047301  0.0989314 ]]
cache [[0.00559205 0.17099392 0.1735822  0.88511161]
 [0.95430019 0.68415479 0.6896189  0.18730555]]
dZ [[ 3.13657102e-05  1.21686252e-02  1.22486953e-02 -1.70190025e-02]
 [-1.45409569e-04 -1.09649340e-02 -1.08034790e-02  1.50595531e-02]]
dW [[-0.00119258 -0.00121259]
 [ 0.00106402  0.00102365]]
db [[ 0.00185742]
 [-0.00171357]]
m 4
6.875398289083531e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00559102, 0.17098478, 0.17357266, 0.88511718],
        [0.95430766, 0.68416969, 0.6896328 , 0.18729986]]), matrix([[6.70928493e-04, 1.02111105e-02, 1.01567623e-02, 9.80091896e-01]])]
dA [[ 1.00067138  1.01031645  1.01026098 -1.02031249]]
cache [[6.70928493e-04 1.02111105e-02 1.01567623e-02 9.80091896e-01]]
dZ [[ 0.00067093  0.01021111  0.01015676 -0.0199081 ]]
dW [[-0.00352709  0.00272551]]
db [[0.00028267]]
m 4
dA [[ 0.00563889  0.08582031  0.08536354 -0.16731968]
 [-0.00333329 -0.05073059 -0.05046058  0.0989069

 [-0.00329855 -0.05025816 -0.04999265  0.09798712]]
cache [[0.00555214 0.17063983 0.17321274 0.88532748]
 [0.95458923 0.68473263 0.69015786 0.18708445]]
dZ [[ 3.07945852e-05  1.20264867e-02  1.21056581e-02 -1.68205785e-02]
 [-1.42987600e-04 -1.08494225e-02 -1.06904277e-02  1.49022597e-02]]
dW [[-0.00117873 -0.00119852]
 [ 0.00105296  0.00101321]]
db [[ 0.00183559]
 [-0.00169514]]
m 4
6.79462795881429e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00555113, 0.17063081, 0.17320334, 0.88533298],
        [0.95459658, 0.68474735, 0.69017159, 0.18707881]]), matrix([[6.62343687e-04, 1.00920559e-02, 1.00387511e-02, 9.80323755e-01]])]
dA [[ 1.00066278  1.01019494  1.01014055 -1.02007117]]
cache [[6.62343687e-04 1.00920559e-02 1.00387511e-02 9.80323755e-01]]
dZ [[ 0.00066234  0.01009206  0.01003875 -0.01967624]]
dW [[-0.0034889   0.00269756]]
db [[0.00027923]]
m 4
dA [[ 0.0055758   0.0849578   0.08450906 -0.16564022]
 [-0.00329764 -0.05024584 -0.04998045  0.09796314

cache [[6.51418721e-04 9.94017124e-03 9.88818643e-03 9.80619543e-01]]
dZ [[ 0.00065142  0.00994017  0.00988819 -0.01938046]]
dW [[-0.00344011  0.00266182]]
db [[0.00027483]]
m 4
dA [[ 0.00549534  0.08385484  0.0834163  -0.16349267]
 [-0.00325216 -0.04962551 -0.04936598  0.09675538]]
cache [[0.00550009 0.17017516 0.17272793 0.88561107]
 [0.95496717 0.6854919  0.69086626 0.18679278]]
dZ [[ 3.00586112e-05  1.18416091e-02  1.19196042e-02 -1.65624785e-02]
 [-1.39858549e-04 -1.06988999e-02 -1.05430953e-02  1.46972619e-02]]
dW [[-0.00116072 -0.00118022]
 [ 0.00103854  0.00099959]]
db [[ 0.0018072 ]
 [-0.00167115]]
m 4
6.689618085920358e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.0054991 , 0.17016631, 0.17271869, 0.88561647],
        [0.95497436, 0.68550638, 0.69087977, 0.18678721]]), matrix([[6.51207831e-04, 9.93723516e-03, 9.88527575e-03, 9.80625260e-01]])]
dA [[ 1.00065163  1.01003697  1.00998397 -1.01975754]]
cache [[6.51207831e-04 9.93723516e-03 9.88527575

db [[0.0002713]]
m 4
dA [[ 0.00543076  0.08296709  0.08253668 -0.1617642 ]
 [-0.00321562 -0.04912584 -0.04887098  0.09578258]]
cache [[0.00545898 0.16980592 0.17234269 0.88583666]
 [0.95526639 0.68609605 0.6914301  0.18655976]]
dZ [[ 2.94845337e-05  1.16960255e-02  1.17730886e-02 -1.63592252e-02]
 [-1.37411452e-04 -1.05801457e-02 -1.04268454e-02  1.45355061e-02]]
dW [[-0.00114653 -0.0011658 ]
 [ 0.00102717  0.00098884]]
db [[ 0.00178484]
 [-0.00165222]]
m 4
6.606964202783918e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00545801, 0.16979719, 0.17233358, 0.885842  ],
        [0.95527345, 0.68611033, 0.69144344, 0.18655424]]), matrix([[6.42462874e-04, 9.81534512e-03, 9.76443579e-03, 9.80862628e-01]])]
dA [[ 1.00064288  1.00991264  1.00986072 -1.01951076]]
cache [[6.42462874e-04 9.81534512e-03 9.76443579e-03 9.80862628e-01]]
dZ [[ 0.00064246  0.00981535  0.00976444 -0.01913737]]
dW [[-0.00339996  0.00263238]]
db [[0.00027122]]
m 4
dA [[ 0.00542924  0.0829461

dZ [[ 0.00063293  0.00968217  0.0096324  -0.01887804]]
dW [[-0.00335707  0.00260092]]
db [[0.00026737]]
m 4
dA [[ 0.00535874  0.08197451  0.08155312 -0.15983171]
 [-0.00317485 -0.04856676 -0.0483171   0.09469417]]
cache [[0.00541298 0.16939039 0.17190915 0.88609081]
 [0.95560195 0.68677679 0.69206562 0.18629621]]
dZ [[ 2.88496968e-05  1.15335911e-02  1.16096085e-02 -1.61324355e-02]
 [-1.34698751e-04 -1.04474111e-02 -1.02968964e-02  1.43546826e-02]]
dW [[-0.00113071 -0.00114971]
 [ 0.00101445  0.00097682]]
db [[ 0.0017599 ]
 [-0.00163108]]
m 4
6.514781715933404e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00541203, 0.1693818 , 0.1719002 , 0.88609606],
        [0.95560887, 0.68679087, 0.69207876, 0.18629075]]), matrix([[6.32730734e-04, 9.67937235e-03, 9.62962485e-03, 9.81127412e-01]])]
dA [[ 1.00063313  1.00977398  1.00972326 -1.01923561]]
cache [[6.32730734e-04 9.67937235e-03 9.62962485e-03 9.81127412e-01]]
dZ [[ 0.00063273  0.00967937  0.00962962 -0.0188

db [[0.00026393]]
m 4
dA [[ 0.00529578  0.08110464  0.08069108 -0.15813816]
 [-0.00313918 -0.04807645 -0.04783131  0.09373966]]
cache [[0.00537263 0.16902383 0.17152673 0.88631523]
 [0.95589692 0.68737805 0.69262709 0.18606255]]
dZ [[ 2.82994130e-05  1.13915334e-02  1.14666313e-02 -1.59340867e-02]
 [-1.32341649e-04 -1.03311225e-02 -1.01830366e-02  1.41962414e-02]]
dW [[-0.00111686 -0.00113564]
 [ 0.0010033   0.00096628]]
db [[ 0.00173809]
 [-0.00161256]]
m 4
6.434196018168289e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.0053717 , 0.16901537, 0.1715179 , 0.88632041],
        [0.95590372, 0.68739194, 0.69264006, 0.18605714]]), matrix([[6.24241061e-04, 9.56047865e-03, 9.51173875e-03, 9.81358932e-01]])]
dA [[ 1.00062463  1.00965276  1.00960308 -1.01899516]]
cache [[6.24241061e-04 9.56047865e-03 9.51173875e-03 9.81358932e-01]]
dZ [[ 0.00062424  0.00956048  0.00951174 -0.01864107]]
dW [[-0.00331783  0.0025721 ]]
db [[0.00026385]]
m 4
dA [[ 0.00529433  0.081084

        [0.95623342, 0.68806725, 0.69327088, 0.18579371]]), matrix([[6.14820215e-04, 9.42823641e-03, 9.38060808e-03, 9.81616439e-01]])]
dA [[ 1.0006152   1.00951797  1.00946944 -1.01872785]]
cache [[6.14820215e-04 9.42823641e-03 9.38060808e-03 9.81616439e-01]]
dZ [[ 0.00061482  0.00942824  0.00938061 -0.01838356]]
dW [[-0.00327513  0.00254073]]
db [[0.00026003]]
m 4
dA [[ 0.00522436  0.08011535  0.07971063 -0.15621219]
 [-0.0030987  -0.04751843 -0.04727838  0.09265338]]
cache [[0.00532671 0.16860419 0.17108893 0.88657241]
 [0.95623342 0.68806725 0.69327088 0.18579371]]
dZ [[ 2.76804603e-05  1.12303148e-02  1.13043637e-02 -1.57089741e-02]
 [-1.29683972e-04 -1.01989146e-02 -1.00535765e-02  1.40160855e-02]]
dW [[-0.00110115 -0.00111966]
 [ 0.00099063  0.00095429]]
db [[ 0.00171335]
 [-0.00159152]]
m 4
6.342777666211829e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00532581, 0.16859587, 0.17108025, 0.88657752],
        [0.95624008, 0.68808092, 0.69328366, 0.1

        [0.95651084, 0.68863811, 0.69380428, 0.18557021]]), matrix([[6.06952308e-04, 9.31754298e-03, 9.27083765e-03, 9.81831979e-01]])]
dA [[ 1.00060732  1.00940518  1.00935759 -1.01850421]]
cache [[6.06952308e-04 9.31754298e-03 9.27083765e-03 9.81831979e-01]]
dZ [[ 0.00060695  0.00931754  0.00927084 -0.01816802]]
dW [[-0.00323935  0.00251442]]
db [[0.00025683]]
m 4
dA [[ 0.00516581  0.07930223  0.07890472 -0.15462923]
 [-0.00306549 -0.04705946 -0.04682357  0.09175994]]
cache [[0.00528894 0.16825703 0.17072676 0.8867854 ]
 [0.95651084 0.68863811 0.69380428 0.18557021]]
dZ [[ 2.71771782e-05  1.10980770e-02  1.11712611e-02 -1.55243199e-02]
 [-1.27517863e-04 -1.00902850e-02 -9.94719389e-03  1.38680389e-02]]
dW [[-0.00108826 -0.00110656]
 [ 0.00098021  0.00094444]]
db [[ 0.00169305]
 [-0.00157424]]
m 4
6.267821826517262e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00528805, 0.16824882, 0.1707182 , 0.88679043],
        [0.95651739, 0.68865161, 0.6938169 , 0.1

dZ [[ 0.00059873  0.00920157  0.00915583 -0.01794221]]
dW [[-0.00320182  0.0024868 ]]
db [[0.00025348]]
m 4
dA [[ 0.00510448  0.07844858  0.07805857 -0.15296743]
 [-0.00303069 -0.0465773  -0.04634574  0.09082139]]
cache [[0.00524926 0.16789033 0.17034421 0.88701057]
 [0.95680291 0.68924178 0.69436849 0.18533306]]
dZ [[ 2.66540853e-05  1.09595145e-02  1.10317884e-02 -1.53308262e-02]
 [-1.25261562e-04 -9.97627687e-03 -9.83553340e-03  1.37126424e-02]]
dW [[-0.00107476 -0.00109283]
 [ 0.00096928  0.00093409]]
db [[ 0.00167178]
 [-0.00155611]]
m 4
6.189308870568343e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00524838, 0.16788224, 0.17033578, 0.88701554],
        [0.95680935, 0.6892551 , 0.69438095, 0.18532782]]), matrix([[5.98546413e-04, 9.19902720e-03, 9.15330252e-03, 9.82062746e-01]])]
dA [[ 1.0005989   1.00928443  1.00923786 -1.01826488]]
cache [[5.98546413e-04 9.19902720e-03 9.15330252e-03 9.82062746e-01]]
dZ [[ 0.00059855  0.00919903  0.0091533  -0.0179

 [0.95709612 0.68985054 0.69493762 0.18509308]]
dZ [[ 2.61359159e-05  1.08211035e-02  1.08924641e-02 -1.51375360e-02]
 [-1.23021472e-04 -9.86220462e-03 -9.72379918e-03  1.35571381e-02]]
dW [[-0.00106127 -0.00107911]
 [ 0.00095833  0.00092373]]
db [[ 0.00165054]
 [-0.00153797]]
m 4
6.110909958842556e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00520865, 0.167513  , 0.1699506 , 0.8872425 ],
        [0.95710243, 0.68986368, 0.69494991, 0.18508789]]), matrix([[5.90353650e-04, 9.08326265e-03, 9.03848827e-03, 9.82288150e-01]])]
dA [[ 1.0005907   1.00916652  1.00912093 -1.01803122]]
cache [[5.90353650e-04 9.08326265e-03 9.03848827e-03 9.82288150e-01]]
dZ [[ 0.00059035  0.00908326  0.00903849 -0.01771185]]
dW [[-0.00316349  0.00245857]]
db [[0.00025006]]
m 4
dA [[ 0.00504193  0.07757579  0.0771934  -0.15126842]
 [-0.00299516 -0.04608399 -0.04585683  0.08986118]]
cache [[0.00520865 0.167513   0.1699506  0.8872425 ]
 [0.95710243 0.68986368 0.69494991 0.18508789]]


        [0.95737785, 0.69043811, 0.69548709, 0.18486065]]), matrix([[5.82709443e-04, 8.97502176e-03, 8.93112909e-03, 9.82498901e-01]])]
dA [[ 1.00058305  1.0090563   1.00901161 -1.01781284]]
cache [[5.82709443e-04 8.97502176e-03 8.93112909e-03 9.82498901e-01]]
dZ [[ 0.00058271  0.00897502  0.00893113 -0.0175011 ]]
dW [[-0.00312838  0.0024327 ]]
db [[0.00024694]]
m 4
dA [[ 0.00498471  0.07677561  0.07640013 -0.14971078]
 [-0.00296265 -0.04563142 -0.04540826  0.08898028]]
cache [[0.00517138 0.16716488 0.16958745 0.88745668]
 [0.95737785 0.69043811 0.69548709 0.18486065]]
dZ [[ 2.56445274e-05  1.06887598e-02  1.07592433e-02 -1.49527112e-02]
 [-1.20892466e-04 -9.75295475e-03 -9.61677815e-03  1.34081885e-02]]
dW [[-0.00104837 -0.00106599]
 [ 0.00094785  0.00091381]]
db [[ 0.00163023]
 [-0.00152061]]
m 4
6.035973865233057e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00517054, 0.16715702, 0.16957926, 0.88746152],
        [0.95738405, 0.69045108, 0.69549922, 0.1

        [0.95763637, 0.69097957, 0.69599358, 0.18464576]]), matrix([[5.75582156e-04, 8.87390118e-03, 8.83082624e-03, 9.82695784e-01]])]
dA [[ 1.00057591  1.00895335  1.0089095  -1.01760892]]
cache [[5.75582156e-04 8.87390118e-03 8.83082624e-03 9.82695784e-01]]
dZ [[ 0.00057558  0.0088739   0.00883083 -0.01730422]]
dW [[-0.00309555  0.00240848]]
db [[0.00024402]]
m 4
dA [[ 0.00493126  0.07602658  0.07565754 -0.14825276]
 [-0.00293227 -0.04520752 -0.04498808  0.08815522]]
cache [[0.00513647 0.16683708 0.16924553 0.88765853]
 [0.95763637 0.69097957 0.69599358 0.18464576]]
dZ [[ 2.51991874e-05  1.05678825e-02  1.06375617e-02 -1.47838935e-02]
 [-1.18958968e-04 -9.65301708e-03 -9.51887038e-03  1.32719182e-02]]
dW [[-0.00103658 -0.001054  ]
 [ 0.00093826  0.00090473]]
db [[ 0.00161169]
 [-0.00150473]]
m 4
5.967552554425742e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00513565, 0.16682933, 0.16923744, 0.88766331],
        [0.95764248, 0.69099238, 0.69600557, 0.1

 [0.95792074 0.69157773 0.69655326 0.1844076 ]]
dZ [[ 2.47154349e-05  1.04355469e-02  1.05043422e-02 -1.45990661e-02]
 [-1.16854321e-04 -9.54343655e-03 -9.41150570e-03  1.31224810e-02]]
dW [[-0.00102368 -0.00104088]
 [ 0.00092774  0.00089476]]
db [[ 0.00159138]
 [-0.00148733]]
m 4
5.892669459634626e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00509734, 0.16646772, 0.16886025, 0.88788619],
        [0.95792673, 0.69159037, 0.69656509, 0.18440256]]), matrix([[5.67632409e-04, 8.76088336e-03, 8.71871549e-03, 9.82915826e-01]])]
dA [[ 1.00056795  1.00883831  1.0087954  -1.01738112]]
cache [[5.67632409e-04 8.76088336e-03 8.71871549e-03 9.82915826e-01]]
dZ [[ 0.00056763  0.00876088  0.00871872 -0.01708417]]
dW [[-0.00305881  0.00238137]]
db [[0.00024076]]
m 4
dA [[ 0.00487154  0.07518772  0.07482583 -0.14661993]
 [-0.00289829 -0.04473248 -0.04451717  0.08723064]]
cache [[0.00509734 0.16646772 0.16886025 0.88788619]
 [0.95792673 0.69159037 0.69656509 0.18440256]]


        [0.9582177 , 0.69220529, 0.69714061, 0.18415687]]), matrix([[5.59724812e-04, 8.64822423e-03, 8.60695329e-03, 9.83135166e-01]])]
dA [[ 1.00056004  1.00872367  1.00868168 -1.01715414]]
cache [[5.59724812e-04 8.64822423e-03 8.60695329e-03 9.83135166e-01]]
dZ [[ 0.00055972  0.00864822  0.00860695 -0.01686483]]
dW [[-0.00302215  0.00235429]]
db [[0.00023752]]
m 4
dA [[ 0.00481201  0.07434972  0.07399491 -0.1449888 ]
 [-0.00286441 -0.0442576  -0.04404639  0.08630639]]
cache [[0.00505821 0.16609631 0.16847285 0.88811532]
 [0.9582177  0.69220529 0.69714061 0.18415687]]
dZ [[ 2.42170426e-05  1.02980546e-02  1.03659278e-02 -1.44070287e-02]
 [-1.14681143e-04 -9.42939676e-03 -9.29976082e-03  1.29669419e-02]]
dW [[-0.00101028 -0.00102724]
 [ 0.0009168   0.00088439]]
db [[ 0.00157029]
 [-0.00146922]]
m 4
5.814894898150458e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00505742, 0.16608879, 0.16846501, 0.88811997],
        [0.95822358, 0.69221775, 0.69715227, 0.1

dW [[-0.00299356  0.00233316]]
db [[0.00023499]]
m 4
dA [[ 0.00476565  0.07369558  0.07334626 -0.14371559]
 [-0.00283801 -0.04388669 -0.04367866  0.08558452]]
cache [[0.00502763 0.16580467 0.16816867 0.8882954 ]
 [0.95844545 0.69268864 0.6975931  0.18396315]]
dZ [[ 2.38394549e-05  1.01930921e-02  1.02602589e-02 -1.42604209e-02]
 [-1.13031402e-04 -9.34220707e-03 -9.21431799e-03  1.28480093e-02]]
dW [[-0.00100004 -0.00101683]
 [ 0.00090842  0.00087645]]
db [[ 0.00155419]
 [-0.00145539]]
m 4
5.75553929975943e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00502685, 0.16579724, 0.16816092, 0.88829999],
        [0.95845125, 0.69270096, 0.69760464, 0.1839582 ]]), matrix([[5.53419904e-04, 8.55822549e-03, 8.51766582e-03, 9.83310384e-01]])]
dA [[ 1.00055373  1.0086321   1.00859084 -1.01697289]]
cache [[5.53419904e-04 8.55822549e-03 8.51766582e-03 9.83310384e-01]]
dZ [[ 0.00055342  0.00855823  0.00851767 -0.01668962]]
dW [[-0.00299283  0.00233262]]
db [[0.00023492]]


dA [[ 1.00054663  1.00852897  1.00848853 -1.0167688 ]]
cache [[5.46330653e-04 8.45684616e-03 8.41708211e-03 9.83507755e-01]]
dZ [[ 0.00054633  0.00845685  0.00841708 -0.01649224]]
dW [[-0.00295977  0.00230817]]
db [[0.000232]]
m 4
dA [[ 0.00471092  0.07292196  0.07257908 -0.14220985]
 [-0.00280682 -0.04344777 -0.04324348  0.08473032]]
cache [[0.00499144 0.16545778 0.16780688 0.88850977]
 [0.95871554 0.69326414 0.698132   0.1837318 ]]
dZ [[ 2.33968954e-05  1.00691738e-02  1.01355039e-02 -1.40873302e-02]
 [-1.11094099e-04 -9.23912395e-03 -9.11329145e-03  1.27073809e-02]]
dW [[-0.00098796 -0.00100454]
 [ 0.00089852  0.00086706]]
db [[ 0.00153519]
 [-0.00143903]]
m 4
5.685484181441961e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00499068, 0.16545045, 0.16779924, 0.8885143 ],
        [0.95872124, 0.6932763 , 0.69814339, 0.1837269 ]]), matrix([[5.46178415e-04, 8.45466694e-03, 8.41491992e-03, 9.83511998e-01]])]
dA [[ 1.00054648  1.00852676  1.00848633 -1.016764

db [[ 0.00151738]
 [-0.00142369]]
m 4
5.619876613617984e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00495669, 0.165123  , 0.16745773, 0.88871683],
        [0.95897536, 0.69382014, 0.69865278, 0.18350758]]), matrix([[5.39408455e-04, 8.35766607e-03, 8.31867461e-03, 9.83700842e-01]])]
dA [[ 1.0005397   1.00842811  1.00838846 -1.01656922]]
cache [[5.39408455e-04 8.35766607e-03 8.31867461e-03 9.83700842e-01]]
dZ [[ 0.00053941  0.00835767  0.00831867 -0.01629916]]
dW [[-0.0029274   0.00228421]]
db [[0.00022915]]
m 4
dA [[ 0.00465853  0.07217992  0.07184318 -0.14076561]
 [-0.00277696 -0.04302651 -0.04282578  0.0839105 ]]
cache [[0.00495669 0.165123   0.16745773 0.88871683]
 [0.95897536 0.69382014 0.69865278 0.18350758]]
dZ [[ 2.29764632e-05  9.95053647e-03  1.00160627e-02 -1.39216100e-02]
 [-1.09249916e-04 -9.14028323e-03 -9.01641375e-03  1.25725234e-02]]
dW [[-0.00097639 -0.00099277]
 [ 0.00088903  0.00085806]]
db [[ 0.00151699]
 [-0.00142336]]
m 4
5.61843461

 [-0.00274583 -0.04258657 -0.04238952  0.08305434]]
cache [[0.00492039 0.16477141 0.16709106 0.88893449]
 [0.95924733 0.6944047  0.69920046 0.18327109]]
dZ [[ 2.25418859e-05  9.82694857e-03  9.89163473e-03 -1.37489683e-02]
 [-1.07339803e-04 -9.03715985e-03 -8.91532904e-03  1.24318052e-02]]
dW [[-0.00096433 -0.0009805 ]
 [ 0.00087912  0.00084866]]
db [[ 0.00149804]
 [-0.00140701]]
m 4
5.548607795057922e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00491966, 0.16476429, 0.16708363, 0.8889389 ],
        [0.95925283, 0.69441655, 0.69921156, 0.18326628]]), matrix([[5.32067263e-04, 8.25227656e-03, 8.21409978e-03, 9.83906013e-01]])]
dA [[ 1.00053235  1.00832094  1.00828213 -1.01635724]]
cache [[5.32067263e-04 8.25227656e-03 8.21409978e-03 9.83906013e-01]]
dZ [[ 0.00053207  0.00825228  0.0082141  -0.01609399]]
dW [[-0.00289296  0.0022587 ]]
db [[0.00022611]]
m 4
dA [[ 0.00460287  0.07138983  0.07105957 -0.13922788]
 [-0.00274521 -0.04257768 -0.04238071  0.0830370

db [[0.00022362]]
m 4
dA [[ 0.00455712  0.07073903  0.07041406 -0.13796128]
 [-0.00271909 -0.04220776 -0.04201386  0.08231716]]
cache [[0.00488912 0.16446704 0.16677365 0.88912307]
 [0.95948203 0.69491128 0.6996752  0.18306552]]
dZ [[ 2.21713659e-05  9.72079001e-03  9.78475232e-03 -1.36006688e-02]
 [-1.05708079e-04 -8.94844976e-03 -8.82836493e-03  1.23107404e-02]]
dW [[-0.00095398 -0.00096997]
 [ 0.00087059  0.00084057]]
db [[ 0.00148176]
 [-0.00139295]]
m 4
5.488645164454367e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.0048884 , 0.16446001, 0.16676632, 0.88912743],
        [0.95948745, 0.69492299, 0.69968618, 0.18306076]]), matrix([[5.25901145e-04, 8.16359130e-03, 8.12609503e-03, 9.84078662e-01]])]
dA [[ 1.00052618  1.00823078  1.00819267 -1.01617893]]
cache [[5.25901145e-04 8.16359130e-03 8.12609503e-03 9.84078662e-01]]
dZ [[ 0.0005259   0.00816359  0.0081261  -0.01592134]]
dW [[-0.00286395  0.0022372 ]]
db [[0.00022356]]
m 4
dA [[ 0.00455604  0.070723

dA [[ 0.00450908  0.07005442  0.06973499 -0.13662891]
 [-0.00269166 -0.0418184  -0.04162772  0.08155948]]
cache [[0.00485696 0.16415259 0.16644574 0.88931806]
 [0.95972379 0.69543515 0.70016627 0.18285232]]
dZ [[ 2.17940535e-05  9.61192346e-03  9.67514136e-03 -1.34485813e-02]
 [-1.04043411e-04 -8.85735094e-03 -8.73905158e-03  1.21864018e-02]]
dW [[-0.00094336 -0.00095916]
 [ 0.00086184  0.00083226]]
db [[ 0.00146507]
 [-0.00137851]]
m 4
5.427168799204598e-07
self.act [array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]]), matrix([[0.00485625, 0.16414564, 0.1664385 , 0.88932236],
        [0.95972911, 0.69544672, 0.70017711, 0.18284761]]), matrix([[5.19589300e-04, 8.07265310e-03, 8.03584982e-03, 9.84255694e-01]])]
dA [[ 1.00051986  1.00813835  1.00810095 -1.01599615]]
cache [[5.19589300e-04 8.07265310e-03 8.03584982e-03 9.84255694e-01]]
dZ [[ 0.00051959  0.00807265  0.00803585 -0.01574431]]
dW [[-0.00283417  0.00221512]]
db [[0.00022095]]
m 4
dA [[ 0.00450802  0.07003936  0.06972005 -0.1365